-- 创建审计日志表
CREATE TABLE IF NOT EXISTS `audit_logs` (
  `id` INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` INT COMMENT '操作员ID',
  `operator_name` VARCHAR(50) COMMENT '操作员用户名',
  `module` VARCHAR(50) NOT NULL COMMENT '操作模块',
  `action` VARCHAR(20) NOT NULL COMMENT '操作类型：CREATE-创建，UPDATE-更新，DELETE-删除',
  `target_type` VARCHAR(50) COMMENT '操作对象类型',
  `target_id` INT COMMENT '操作对象ID',
  `target_name` VARCHAR(255) COMMENT '操作对象名称',
  `description` TEXT COMMENT '操作描述',
  `old_data` TEXT COMMENT '操作前数据（JSON）',
  `new_data` TEXT COMMENT '操作后数据（JSON）',
  `ip_address` VARCHAR(50) COMMENT 'IP地址',
  `user_agent` VARCHAR(255) COMMENT '用户代理',
  `status` VARCHAR(20) DEFAULT 'success' COMMENT '状态：success-成功，failed-失败',
  `error_message` TEXT COMMENT '错误信息（如有）',
  INDEX `idx_module` (`module`),
  INDEX `idx_action` (`action`),
  INDEX `idx_operator_id` (`operator_id`),
  INDEX `idx_created_at` (`created_at`),
  INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='审计日志表';
